// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_l207jtUuTlSBH1MRTJX0D0L43LL47kw',
    appId: '1:739464163677:web:c55a661530caf42b3ab8b4',
    messagingSenderId: '739464163677',
    projectId: 'solarapp-842eb',
    authDomain: 'solarapp-842eb.firebaseapp.com',
    storageBucket: 'solarapp-842eb.appspot.com',
    measurementId: 'G-BVS3VV68WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTPSZ8Z9pXOvJ0OfO7hW6PtZjYsRva6fw',
    appId: '1:739464163677:android:bc66713e827ae1803ab8b4',
    messagingSenderId: '739464163677',
    projectId: 'solarapp-842eb',
    storageBucket: 'solarapp-842eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBldjN2ClElw0zdKG6hR4fkcWsCTzVxID4',
    appId: '1:739464163677:ios:10416ff793dfcad03ab8b4',
    messagingSenderId: '739464163677',
    projectId: 'solarapp-842eb',
    storageBucket: 'solarapp-842eb.appspot.com',
    iosBundleId: 'com.example.solarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBldjN2ClElw0zdKG6hR4fkcWsCTzVxID4',
    appId: '1:739464163677:ios:82c1f5ddb07c431f3ab8b4',
    messagingSenderId: '739464163677',
    projectId: 'solarapp-842eb',
    storageBucket: 'solarapp-842eb.appspot.com',
    iosBundleId: 'com.example.solarApp.RunnerTests',
  );
}
